version: "3.1"
services:
    mongo-server:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        container_name: mongo-server
        ports:
            - "27017:27017"
        volumes:
            - "${HOME}/.mongo/data/db:/data/db"
            - "./conf:/etc/mongo"
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: dxfundmongo
        command: --config /etc/mongo/mongo.conf
    mongo-arbiter:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        container_name: mongo-arbiter
        ports:
            - "27018:27017"
        volumes:
            - "${HOME}/.mongo/arbdata/db:/data/db"
            - "./conf:/etc/mongo"
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: dxfundmongo
        command: --config /etc/mongo/mongo.conf
