version: '2.0'
services:
    mysql:
        image: mysql
        restart: always
        container_name: mysql_server
        ports:
            - "3306:3306"
        volumes:
            #- "./conf:/my/custom:/etc/mysql/conf.d"
            - "${HOME}/.docker_mysql/.data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-joker_root}
