version: '3.1'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: dx-zookeeper
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=192.168.15.201:2888:3888 server.2=0.0.0.0:2888:3888 server.3=192.168.15.203:2888:3888
        volumes:
            - ${HOME}/.dx-zk/datalog:/datalog
            - ${HOME}/.dx-zk/data:/data

